// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef _ESP32_GUI_UI_H
#define _ESP32_GUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void SpinAndLargen_Animation(lv_obj_t * TargetObject, int delay);
void LargeBtn_Animation(lv_obj_t * TargetObject, int delay);
void MoveColorToCenter_Animation(lv_obj_t * TargetObject, int delay);
void MoveSettingsToCenter_Animation(lv_obj_t * TargetObject, int delay);
void HideBtn_Animation(lv_obj_t * TargetObject, int delay);
void ShowBtn_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Home_Scr
void ui_Home_Scr_screen_init(void);
extern lv_obj_t * ui_Home_Scr;
extern lv_obj_t * ui_Overlay;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
void ui_event_Button_text(lv_event_t * e);
extern lv_obj_t * ui_Button_text;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_Temp;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image3;
// SCREEN: ui_Parking_assistant
void ui_Parking_assistant_screen_init(void);
extern lv_obj_t * ui_Parking_assistant;
extern lv_obj_t * ui_Overlay2;
void ui_event_main_display_button(lv_event_t * e);
extern lv_obj_t * ui_main_display_button;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_auto;
extern lv_obj_t * ui_senzorFlag1;
extern lv_obj_t * ui_senzorFlag2;
extern lv_obj_t * ui_senzorFlag3;
extern lv_obj_t * ui_senzorFlag4;
void ui_event_Camera_View(lv_event_t * e);
extern lv_obj_t * ui_Camera_View;
extern lv_obj_t * ui_Camera_View1;
// SCREEN: ui_Warning_Scr
void ui_Warning_Scr_screen_init(void);
extern lv_obj_t * ui_Warning_Scr;
extern lv_obj_t * ui_Overlay1;
extern lv_obj_t * ui_Time1;
extern lv_obj_t * ui_Temp1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_wifi_2_yes_png);    // assets/wifi_2_yes.png
LV_IMG_DECLARE(ui_img_auto_2_png);    // assets/auto_2.png
LV_IMG_DECLARE(ui_img_linije_2_png);    // assets/linije_2.png
LV_IMG_DECLARE(ui_img_linije_2_png);    // assets/linije_2.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
