// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

void ui_Home_Scr_screen_init( void )
{
    ui_Home_Scr = lv_obj_create( NULL );
    lv_obj_clear_flag( ui_Home_Scr, LV_OBJ_FLAG_SCROLLABLE ); /// Flags
    lv_obj_set_style_bg_color( ui_Home_Scr, lv_color_hex( 0x343434 ), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa( ui_Home_Scr, 255, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_grad_color( ui_Home_Scr, lv_color_hex( 0x000000 ), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_grad_dir( ui_Home_Scr, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT );

    ui_Overlay = lv_obj_create( ui_Home_Scr );
    lv_obj_set_width( ui_Overlay, 320 );
    lv_obj_set_height( ui_Overlay, 240 );
    lv_obj_set_align( ui_Overlay, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_Overlay, LV_OBJ_FLAG_SCROLLABLE ); /// Flags
    lv_obj_set_style_bg_color( ui_Overlay, lv_color_hex( 0x000000 ), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa( ui_Overlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT );

    ui_Button1 = lv_btn_create( ui_Home_Scr );
    lv_obj_set_width( ui_Button1, 129 );
    lv_obj_set_height( ui_Button1, 50 );
    lv_obj_set_x( ui_Button1, 1 );
    lv_obj_set_y( ui_Button1, 73 );
    lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
    lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS ); /// Flags
    lv_obj_clear_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE ); /// Flags

    ui_Button_text = lv_label_create( ui_Button1 );
    lv_obj_set_width( ui_Button_text, LV_SIZE_CONTENT ); /// 1
    lv_obj_set_height( ui_Button_text, LV_SIZE_CONTENT ); /// 1
    lv_obj_set_x( ui_Button_text, 1 );
    lv_obj_set_y( ui_Button_text, 0 );
    lv_obj_set_align( ui_Button_text, LV_ALIGN_CENTER );
    lv_label_set_text( ui_Button_text, "Parking assistant" );

    ui_Time = lv_label_create( ui_Home_Scr );
    lv_obj_set_width( ui_Time, LV_SIZE_CONTENT ); /// 1
    lv_obj_set_height( ui_Time, LV_SIZE_CONTENT ); /// 1
    lv_obj_set_align( ui_Time, LV_ALIGN_CENTER );
    lv_label_set_text( ui_Time, "Loading time..." );
    lv_obj_set_style_text_color( ui_Time, lv_color_hex( 0xFFFFFF ), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa( ui_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_font( ui_Time, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT );

    ui_Temp = lv_label_create( ui_Home_Scr );
    lv_obj_set_width( ui_Temp, LV_SIZE_CONTENT ); /// 1
    lv_obj_set_height( ui_Temp, LV_SIZE_CONTENT ); /// 1
    lv_obj_set_x( ui_Temp, -8 );
    lv_obj_set_y( ui_Temp, -93 );
    lv_obj_set_align( ui_Temp, LV_ALIGN_CENTER );
    lv_label_set_text( ui_Temp, "Loading temp..." );
    lv_obj_set_style_text_color( ui_Temp, lv_color_hex( 0xFFFFFF ), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa( ui_Temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT );

    ui_Image1 = lv_img_create( ui_Home_Scr );
    lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT ); /// 1
    lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT ); /// 1
    lv_obj_set_x( ui_Image1, 131 );
    lv_obj_set_y( ui_Image1, -99 );
    lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
    lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST ); /// Flags
    lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE ); /// Flags

    ui_Image3 = lv_img_create( ui_Home_Scr );
    lv_img_set_src( ui_Image3, &ui_img_wifi_2_yes_png );
    lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT ); /// 1
    lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT ); /// 1
    lv_obj_set_x( ui_Image3, 131 );
    lv_obj_set_y( ui_Image3, -99 );
    lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
    lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST ); /// Flags
    lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE ); /// Flags

    lv_obj_add_event_cb( ui_Button_text, ui_event_Button_text, LV_EVENT_ALL, NULL );
    lv_obj_add_event_cb( ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL );

}
