// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

void ui_Parking_assistant_screen_init(void)
{
    ui_Parking_assistant = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Parking_assistant, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Parking_assistant, lv_color_hex(0x343434), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Parking_assistant, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Parking_assistant, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Parking_assistant, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Overlay2 = lv_obj_create(ui_Parking_assistant);
    lv_obj_set_width(ui_Overlay2, 320);
    lv_obj_set_height(ui_Overlay2, 240);
    lv_obj_set_align(ui_Overlay2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Overlay2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Overlay2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Overlay2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_display_button = lv_btn_create(ui_Parking_assistant);
    lv_obj_set_width(ui_main_display_button, 100);
    lv_obj_set_height(ui_main_display_button, 50);
    lv_obj_set_x(ui_main_display_button, -57);
    lv_obj_set_y(ui_main_display_button, 82);
    lv_obj_set_align(ui_main_display_button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_main_display_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_main_display_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_main_display_button);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 1);
    lv_obj_set_y(ui_Label2, 2);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Main Screen");

    ui_auto = lv_img_create(ui_Parking_assistant);
    lv_img_set_src(ui_auto, &ui_img_auto_2_png);
    lv_obj_set_width(ui_auto, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_height(ui_auto, LV_SIZE_CONTENT);    /// 150
    lv_obj_set_x(ui_auto, -60);
    lv_obj_set_y(ui_auto, 0);
    lv_obj_set_align(ui_auto, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_auto, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_auto, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_auto, -900);

    ui_senzorFlag1 = lv_img_create(ui_Parking_assistant);
    lv_img_set_src(ui_senzorFlag1, &ui_img_linije_2_png);
    lv_obj_set_width(ui_senzorFlag1, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_height(ui_senzorFlag1, LV_SIZE_CONTENT);    /// 150
    lv_obj_set_x(ui_senzorFlag1, 60);
    lv_obj_set_y(ui_senzorFlag1, 0);
    lv_obj_set_align(ui_senzorFlag1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_senzorFlag1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_senzorFlag1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_senzorFlag1, -900);

    ui_senzorFlag2 = lv_img_create(ui_Parking_assistant);
    lv_img_set_src(ui_senzorFlag2, &ui_img_linije_2_png);
    lv_obj_set_width(ui_senzorFlag2, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_height(ui_senzorFlag2, LV_SIZE_CONTENT);    /// 150
    lv_obj_set_x(ui_senzorFlag2, 90);
    lv_obj_set_y(ui_senzorFlag2, 0);
    lv_obj_set_align(ui_senzorFlag2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_senzorFlag2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_senzorFlag2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_senzorFlag2, -900);

    ui_senzorFlag3 = lv_img_create(ui_Parking_assistant);
    lv_img_set_src(ui_senzorFlag3, &ui_img_linije_2_png);
    lv_obj_set_width(ui_senzorFlag3, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_height(ui_senzorFlag3, LV_SIZE_CONTENT);    /// 150
    lv_obj_set_x(ui_senzorFlag3, 120);
    lv_obj_set_y(ui_senzorFlag3, 0);
    lv_obj_set_align(ui_senzorFlag3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_senzorFlag3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_senzorFlag3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_senzorFlag3, -900);

    ui_senzorFlag4 = lv_img_create(ui_Parking_assistant);
    lv_img_set_src(ui_senzorFlag4, &ui_img_linije_2_png);
    lv_obj_set_width(ui_senzorFlag4, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_height(ui_senzorFlag4, LV_SIZE_CONTENT);    /// 150
    lv_obj_set_x(ui_senzorFlag4, 150);
    lv_obj_set_y(ui_senzorFlag4, 0);
    lv_obj_set_align(ui_senzorFlag4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_senzorFlag4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_senzorFlag4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_senzorFlag4, -900);

    ui_Camera_View = lv_btn_create(ui_Parking_assistant);
    lv_obj_set_width(ui_Camera_View, 100);
    lv_obj_set_height(ui_Camera_View, 50);
    lv_obj_set_x(ui_Camera_View, 64);
    lv_obj_set_y(ui_Camera_View, 83);
    lv_obj_set_align(ui_Camera_View, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Camera_View, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Camera_View, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Camera_View1 = lv_label_create(ui_Camera_View);
    lv_obj_set_width(ui_Camera_View1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Camera_View1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Camera_View1, -1);
    lv_obj_set_y(ui_Camera_View1, 2);
    lv_obj_set_align(ui_Camera_View1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Camera_View1, "Camera View");

    lv_obj_add_event_cb(ui_main_display_button, ui_event_main_display_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Camera_View, ui_event_Camera_View, LV_EVENT_ALL, NULL);

}
