// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

void ui_Warning_Scr_screen_init( void )
{
    ui_Warning_Scr = lv_obj_create( NULL );
    lv_obj_clear_flag( ui_Warning_Scr, LV_OBJ_FLAG_SCROLLABLE ); /// Flags
    lv_obj_set_style_bg_color( ui_Warning_Scr, lv_color_hex( 0x343434 ), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa( ui_Warning_Scr, 255, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_grad_color( ui_Warning_Scr, lv_color_hex( 0x000000 ), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_grad_dir( ui_Warning_Scr, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT );

    ui_Overlay1 = lv_obj_create( ui_Warning_Scr );
    lv_obj_set_width( ui_Overlay1, 320 );
    lv_obj_set_height( ui_Overlay1, 240 );
    lv_obj_set_align( ui_Overlay1, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_Overlay1, LV_OBJ_FLAG_SCROLLABLE ); /// Flags
    lv_obj_set_style_bg_color( ui_Overlay1, lv_color_hex( 0x000000 ), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa( ui_Overlay1, 0, LV_PART_MAIN | LV_STATE_DEFAULT );

    ui_Time1 = lv_label_create( ui_Warning_Scr );
    lv_obj_set_width( ui_Time1, LV_SIZE_CONTENT ); /// 1
    lv_obj_set_height( ui_Time1, LV_SIZE_CONTENT ); /// 1
    lv_obj_set_x( ui_Time1, 37 );
    lv_obj_set_y( ui_Time1, -93 );
    lv_obj_set_align( ui_Time1, LV_ALIGN_CENTER );
    lv_label_set_text( ui_Time1, "Loading time..." );
    lv_obj_set_style_text_color( ui_Time1, lv_color_hex( 0xFFFFFF ), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa( ui_Time1, 255, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_font( ui_Time1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT );

    ui_Temp1 = lv_label_create( ui_Warning_Scr );
    lv_obj_set_width( ui_Temp1, LV_SIZE_CONTENT ); /// 1
    lv_obj_set_height( ui_Temp1, LV_SIZE_CONTENT ); /// 1
    lv_obj_set_x( ui_Temp1, -89 );
    lv_obj_set_y( ui_Temp1, -92 );
    lv_obj_set_align( ui_Temp1, LV_ALIGN_CENTER );
    lv_label_set_text( ui_Temp1, "Loading temp..." );
    lv_obj_set_style_text_color( ui_Temp1, lv_color_hex( 0xFFFFFF ), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa( ui_Temp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT );

    ui_Image2 = lv_img_create( ui_Warning_Scr );
    lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT ); /// 1
    lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT ); /// 1
    lv_obj_set_x( ui_Image2, 131 );
    lv_obj_set_y( ui_Image2, -99 );
    lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
    lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST ); /// Flags
    lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE ); /// Flags

    ui_Image4 = lv_img_create( ui_Warning_Scr );
    lv_img_set_src( ui_Image4, &ui_img_wifi_2_yes_png );
    lv_obj_set_width( ui_Image4, LV_SIZE_CONTENT ); /// 1
    lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT ); /// 1
    lv_obj_set_x( ui_Image4, 131 );
    lv_obj_set_y( ui_Image4, -99 );
    lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
    lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST ); /// Flags
    lv_obj_clear_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE ); /// Flags

    ui_Label4 = lv_label_create( ui_Warning_Scr );
    lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT ); /// 1
    lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT ); /// 1
    lv_obj_set_x( ui_Label4, -1 );
    lv_obj_set_y( ui_Label4, 5 );
    lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
    lv_label_set_text( ui_Label4, "Warning:\nSide Line Crossed!" );
    lv_obj_set_style_text_color( ui_Label4, lv_color_hex( 0xFFFFFF ), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa( ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_align( ui_Label4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_font( ui_Label4, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT );

}
